name: ora
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
#  sdk: '>=2.19.6 <3.0.0'
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0
  isar: 3.0.5
  json_annotation: ^4.8.0
  slugid: ^1.1.0
  get_it: ^8.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  isar_generator: 3.0.5
  build_runner: ^2.3.3
  json_serializable: ^6.3.1