b:
	dart run build_runner build --delete-conflicting-outputs

w:
    dart run build_runner watch --delete-conflicting-outputs

deps:
  dart run build_runner build --delete-conflicting-outputs
  cd ../xcsdrift && dart run build_runner build --delete-conflicting-outputs

db:
  open /Users/xiaofeiwu/Library/Containers/com.example.dummyapp/Data/Documents/sampleNotes.sqlite

