name: xcsmachine
description: "xcs-machine package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

#isar_version: &isar_version 3.0.5 # define the version to be used
#isar_version: &isar_version 3.1.0+1
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0
  dio: ^5.7.0
  path: ^1.8.0
  equatable: ^2.0.5
  recase: ^4.0.0
  slugid: ^1.1.0
  tuple: ^2.0.0
  quiver: ^3.2.1
  decimal: ^2.2.0
  duration: ^3.0.11
  intl: ^0.19.0
  validators: ^3.0.0
  power_extensions: ^0.2.2
#  get_it: ^7.6.0
  get_it: ^8.0.3
  dart_jsonwebtoken: ^2.6.2
  json_path: ^0.7.4
  rxdart: ^0.28.0
  hive: ^2.2.3
  drift: ^2.21.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.0.0
  # https://docs-v2.riverpod.dev/zh-Hans/docs/getting_started
#  riverpod: ^2.3.6
#  riverpod_annotation: ^2.1.1
  # riverpod: ^2.5.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  clock: any
  copy_with_extension: ^4.0.3
#  isar: *isar_version
  timeago: ^3.3.0
  faker: ^2.2.0
  mqtt_client: any
  xcsproto:
    path: ../xcsproto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#  pedantic:
  test:
  json_serializable: ^6.3.0
  build_runner:
  hive_generator: any
  freezed:
  # https://docs-v2.riverpod.dev/zh-Hans/docs/getting_started
  # custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
#  isar_generator: *isar_version
#  analyzer: ^6.8.0

# https://github.com/dart-lang/sdk/blob/main/docs/Flutter-Pinned-Packages.md
#dependency_overrides:
#  collection: ^1.19.0

flutter:
