name: mitubekit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.9.0
  dio: ^5.7.0
  path_provider: ^2.1.5
  path: ^1.9.0

  xcsmachine:
    path: ../xcsmachine
  xcsproto:
    path: ../xcsproto

  stash: ^5.2.0
  stash_memory: ^5.2.0
  stash_file: ^5.2.0
  stash_dio: ^5.2.0

  get_it: ^8.0.3
  sembast: ^3.8.0+1
  json_path: ^0.7.4
  dio_cache_interceptor: ^3.5.1

  form_builder_validators: ^10.0.1
  flutter_form_builder: ^9.7.0
  flutter_hooks: ^0.20.5
  form_builder_extra_fields: ^11.1.0
  equatable: ^2.0.7
  meta: ^1.15.0
  quiver: ^3.2.1
  events_emitter: ^0.0.7

  window_size:
    #    git:
    #      url: https://github.com/google/flutter-desktop-embedding.git
    #      path: plugins/window_size
    path: ../flutter-desktop-embedding/plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.3.0

flutter:
  uses-material-design: true
