name: mitubekit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.9.0
  dio: ^5.7.0
  path_provider: ^2.1.5
  path: ^1.9.0

  xcsmachine:
    path: ../xcsmachine
  xcsproto:
    path: ../xcsproto

  stash: ^5.2.0
  stash_memory: ^5.2.0
  stash_file: ^5.2.0
  stash_dio: ^5.2.0

  get_it: ^8.0.3
  sembast: ^3.8.0+1
  json_path: ^0.7.4
  dio_cache_interceptor: ^3.5.1

  form_builder_validators: ^10.0.1
  flutter_form_builder: ^9.7.0
  flutter_hooks: ^0.20.5
  form_builder_extra_fields: ^11.1.0
  equatable: ^2.0.7
  meta: ^1.15.0
  quiver: ^3.2.1
  events_emitter: ^0.0.7
  dart_nats: ^0.6.5

  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4

  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0

  window_size:
    #    git:
    #      url: https://github.com/google/flutter-desktop-embedding.git
    #      path: plugins/window_size
    path: ../flutter-desktop-embedding/plugins/window_size
  clickup_fading_scroll:
    git:
      url: https://github.com/clickup/clickup_fading_scroll.git
  timeago: ^3.7.0
  ficonsax: ^0.0.3

  action_slider: ^0.7.0
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.3.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/tesla.png
    - assets/charging.png
    - assets/charging_station.png
    - assets/number_plate.png
    - assets/profile.png
    # folder
    - assets/icons/
    # scenaries list
    - assets/scenary/scenary0.png
    - assets/scenary/scenary1.png
    - assets/scenary/scenary2.png
    - assets/scenary/scenary3.png
    - assets/scenary/scenary4.png
    - assets/scenary/scenary5.png
    - assets/scenary/scenary6.png
    - assets/scenary/scenary7.png
    - assets/scenary/scenary8.png
    - assets/scenary/scenary9.png
    - assets/scenary/scenary10.png
    - assets/scenary/scenary11.png
    - assets/scenary/scenary12.png
    - assets/scenary/scenary13.png
    - assets/scenary/scenary14.png
    - assets/scenary/scenary15.png
