name: xcsproto
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  async: ^2.2.0
  # grpc: ^3.0.2
  # protobuf: ^2.0.0
  grpc: ^4.0.1
  protobuf: ^3.1.0
  logging: ^1.0.2
  recase: ^4.0.0
  slugid: ^1.1.0
  args: ^2.3.0
  decimal: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.0.0
  test:
