b file:
  dart compile exe {{file}}

cli:
  dart compile exe bin/xcscli.dart
  ./bin/xcscli.exe

gen:
  dart compile exe bin/xcsgen.dart
  ./bin/xcsgen.exe faker -n nick

buy:
  dart compile exe bin/xcsbuy.dart
  ./bin/xcsbuy.exe get
