b file:
  dart compile exe {{file}}

cli:
  dart compile exe bin/xcscli.dart
  ./bin/xcscli.exe

gen:
  dart compile exe bin/xcsgen.dart
  ./bin/xcsgen.exe faker -n nick

buy:
  dart compile exe bin/xcsbuy.dart
  ./bin/xcsbuy.exe get

exa:
  dart compile exe bin/xcsexa.dart
  ./bin/xcsexa.exe example -s pub

genlogin:
  dart run bin/xcsgen.dart security -n gentoken -l login

cleandb:
  rm /Users/xiaofeiwu/Library/Containers/com.example.dummyapp/Data/Documents/sampleNotes.sqlite
