name: xcsconsole
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  drift: ^2.21.0
  # it is important that drift_dev is a regular dependency here.
  drift_dev: ^2.21.0
  quiver: ^3.2.2
  xcsmachine:
    path: ../xcsmachine
  xcsdrift:
    path: ../xcsdrift
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  recase: ^4.1.0
  args: ^2.5.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.3.0
  # for riverpod
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
