name: xcsapi
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
#  sdk: '>=2.12.0 <3.0.0'
  sdk: ">=3.0.0 <4.0.0"

isar_version: &isar_version 3.0.5 # define the version to be used

dependencies:
  crypto: ^3.0.0
  dio: ^5.1.2
  path: ^1.8.0
  equatable: ^2.0.5
  recase: ^4.0.0
  slugid: ^1.1.0
  tuple: ^2.0.0
  quiver: ^3.2.1
  decimal: ^2.2.0
  duration: ^3.0.11
  intl: ^0.19.0
  validators: ^3.0.0
  power_extensions: ^0.2.2
  get_it: ^8.0.3
  dart_jsonwebtoken: ^2.6.2
  rxdart: ^0.27.5
  hive: ^2.2.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.0.0
  # https://docs-v2.riverpod.dev/zh-Hans/docs/getting_started
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  clock: any
  copy_with_extension: ^4.0.3
  isar: *isar_version
  timeago: ^3.3.0
  mqtt_client: any
  xcsproto:
    path: ../xcsproto

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  json_serializable: ^6.3.0
  build_runner: ^2.1.8
  hive_generator: any
  freezed: ^2.1.0+1
  # https://docs-v2.riverpod.dev/zh-Hans/docs/getting_started
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  isar_generator: *isar_version


