name: xcsapi
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
#  sdk: '>=2.12.0 <3.0.0'
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.1.2
  path: ^1.8.0
  equatable: ^2.0.5
  recase: ^4.0.0
  slugid: ^1.1.0
  tuple: ^2.0.0
  decimal: ^2.2.0
  duration: ^3.0.11
  intl: ^0.18.0
  validators: ^3.0.0
  power_extensions: ^0.2.2
  get_it: ^7.6.0
  dart_jsonwebtoken: ^2.6.2
  rxdart: ^0.27.5
  hive: ^2.2.3
  json_annotation: ^4.8.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
  hive_generator: any


