import '../bundle_meta.dart';
import '../ent/product.dart';


final productProfile = BundleMeta(
    'Product',
    EntityMeta(
        "Product",
        [
          FieldMeta("productId", "id"),
          FieldMeta("productTypeId", "id"),
          FieldMeta("primaryProductCategoryId", "id"),
          FieldMeta("facilityId", "id"),
          FieldMeta("introductionDate", "date-time"),
          FieldMeta("releaseDate", "date-time"),
          FieldMeta("supportDiscontinuationDate", "date-time"),
          FieldMeta("salesDiscontinuationDate", "date-time"),
          FieldMeta("salesDiscWhenNotAvail", "indicator"),
          FieldMeta("internalName", "description"),
          FieldMeta("brandName", "name"),
          FieldMeta("comments", "comment"),
          FieldMeta("productName", "name"),
          FieldMeta("description", "description"),
          FieldMeta("longDescription", "very-long"),
          FieldMeta("priceDetailText", "description"),
          FieldMeta("smallImageUrl", "url"),
          FieldMeta("mediumImageUrl", "url"),
          FieldMeta("largeImageUrl", "url"),
          FieldMeta("detailImageUrl", "url"),
          FieldMeta("originalImageUrl", "url"),
          FieldMeta("detailScreen", "long-varchar"),
          FieldMeta("inventoryMessage", "description"),
          FieldMeta("inventoryItemTypeId", "id"),
          FieldMeta("requireInventory", "indicator"),
          FieldMeta("quantityUomId", "id"),
          FieldMeta("quantityIncluded", "fixed-point"),
          FieldMeta("piecesIncluded", "numeric"),
          FieldMeta("requireAmount", "indicator"),
          FieldMeta("fixedAmount", "currency-amount"),
          FieldMeta("amountUomTypeId", "id"),
          FieldMeta("weightUomId", "id"),
          FieldMeta("shippingWeight", "fixed-point"),
          FieldMeta("productWeight", "fixed-point"),
          FieldMeta("heightUomId", "id"),
          FieldMeta("productHeight", "fixed-point"),
          FieldMeta("shippingHeight", "fixed-point"),
          FieldMeta("widthUomId", "id"),
          FieldMeta("productWidth", "fixed-point"),
          FieldMeta("shippingWidth", "fixed-point"),
          FieldMeta("depthUomId", "id"),
          FieldMeta("productDepth", "fixed-point"),
          FieldMeta("shippingDepth", "fixed-point"),
          FieldMeta("diameterUomId", "id"),
          FieldMeta("productDiameter", "fixed-point"),
          FieldMeta("productRating", "fixed-point"),
          FieldMeta("ratingTypeEnum", "id"),
          FieldMeta("returnable", "indicator"),
          FieldMeta("taxable", "indicator"),
          FieldMeta("chargeShipping", "indicator"),
          FieldMeta("autoCreateKeywords", "indicator"),
          FieldMeta("includeInPromotions", "indicator"),
          FieldMeta("isVirtual", "indicator"),
          FieldMeta("isVariant", "indicator"),
          FieldMeta("virtualVariantMethodEnum", "id"),
          FieldMeta("originGeoId", "id"),
          FieldMeta("requirementMethodEnumId", "id"),
          FieldMeta("billOfMaterialLevel", "numeric"),
          FieldMeta("reservMaxPersons", "fixed-point"),
          FieldMeta("reserv2ndPPPerc", "fixed-point"),
          FieldMeta("reservNthPPPerc", "fixed-point"),
          FieldMeta("configId", "id"),
          FieldMeta("createdDate", "date-time"),
          FieldMeta("createdByUserLogin", "id-vlong"),
          FieldMeta("lastModifiedDate", "date-time"),
          FieldMeta("lastModifiedByUserLogin", "id-vlong"),
          FieldMeta("inShippingBox", "indicator"),
          FieldMeta("defaultShipmentBoxTypeId", "id"),
          FieldMeta("lotIdFilledIn", "long-varchar"),
          FieldMeta("orderDecimalQuantity", "indicator"),
          FieldMeta("lastUpdatedTxStamp", "date-time"),
          FieldMeta("createdTxStamp", "date-time"),
          FieldMeta("tenantId", "id"),
          FieldMeta("cats", "strings"),
          FieldMeta("evict", "boolean"),
          FieldMeta("tag1", "name"),
          FieldMeta("tag2", "name"),
          FieldMeta("tag3", "name"),
          FieldMeta("moreTags", "strings"),
          FieldMeta("jointers", "string-map"),
          FieldMeta("acl", "string-multimap"),
          FieldMeta("resourceId", "id-vlong"),
          FieldMeta("resourceType", "id-long"),
          FieldMeta("xcPrimaryProductCategoryId", "xid"),
          FieldMeta("xcFacilityId", "xid"),
          FieldMeta("xcCreatedByUserLogin", "xid"),
          FieldMeta("xcLastModifiedByUserLogin", "xid"),
        ],
        'productId',
    ),
    {},    
    cast: (json) => Product.fromJson(json),
    list: (List rs) => rs.map((e) => Product.fromJson(e)).toList()
);



