import '../bundle_meta.dart';
import '../ent/shipment.dart';


final shipmentProfile = BundleMeta(
    'Shipment',
    EntityMeta(
        "Shipment",
        [
          FieldMeta("shipmentId", "id"),
          FieldMeta("shipmentTypeId", "id"),
          FieldMeta("statusId", "id"),
          FieldMeta("primaryOrderId", "id"),
          FieldMeta("primaryReturnId", "id"),
          FieldMeta("primaryShipGroupSeqId", "id"),
          FieldMeta("picklistBinId", "id"),
          FieldMeta("estimatedReadyDate", "date-time"),
          FieldMeta("estimatedShipDate", "date-time"),
          FieldMeta("estimatedShipWorkEffId", "id"),
          FieldMeta("estimatedArrivalDate", "date-time"),
          FieldMeta("estimatedArrivalWorkEffId", "id"),
          FieldMeta("latestCancelDate", "date-time"),
          FieldMeta("estimatedShipCost", "currency-amount"),
          FieldMeta("currencyUomId", "id"),
          FieldMeta("handlingInstructions", "long-varchar"),
          FieldMeta("originFacilityId", "id"),
          FieldMeta("destinationFacilityId", "id"),
          FieldMeta("originContactMechId", "id"),
          FieldMeta("originTelecomNumberId", "id"),
          FieldMeta("destinationContactMechId", "id"),
          FieldMeta("destinationTelecomNumberId", "id"),
          FieldMeta("partyIdTo", "id"),
          FieldMeta("partyIdFrom", "id"),
          FieldMeta("additionalShippingCharge", "currency-amount"),
          FieldMeta("addtlShippingChargeDesc", "long-varchar"),
          FieldMeta("createdDate", "date-time"),
          FieldMeta("createdByUserLogin", "id-vlong"),
          FieldMeta("lastModifiedDate", "date-time"),
          FieldMeta("lastModifiedByUserLogin", "id-vlong"),
          FieldMeta("lastUpdatedTxStamp", "date-time"),
          FieldMeta("createdTxStamp", "date-time"),
          FieldMeta("tenantId", "id"),
          FieldMeta("shipBinId", "id"),
          FieldMeta("ncopies", "fixed-point"),
          FieldMeta("accountId", "id"),
          FieldMeta("tokenId", "id"),
          FieldMeta("origin", "indicator"),
          FieldMeta("shipmentErcId", "id"),
          FieldMeta("evict", "boolean"),
          FieldMeta("tag1", "name"),
          FieldMeta("tag2", "name"),
          FieldMeta("tag3", "name"),
          FieldMeta("moreTags", "strings"),
          FieldMeta("acl", "string-multimap"),
          FieldMeta("resourceId", "id-vlong"),
          FieldMeta("resourceType", "id-long"),
          FieldMeta("xcEstimatedShipWorkEffId", "xid"),
          FieldMeta("xcEstimatedArrivalWorkEffId", "xid"),
          FieldMeta("xcOriginFacilityId", "xid"),
          FieldMeta("xcDestinationFacilityId", "xid"),
          FieldMeta("xcOriginContactMechId", "xid"),
          FieldMeta("xcDestinationContactMechId", "xid"),
          FieldMeta("xcPrimaryOrderId", "xid"),
          FieldMeta("xcPrimaryReturnId", "xid"),
          FieldMeta("xcPicklistBinId", "xid"),
          FieldMeta("xcPartyIdTo", "xid"),
          FieldMeta("xcPartyIdFrom", "xid"),
          FieldMeta("xcShipBinId", "xid"),
          FieldMeta("xcShipmentErcId", "xid"),
        ],
        'shipmentId',
    ),
    {},    
    cast: (json) => Shipment.fromJson(json),
    list: (List rs) => rs.map((e) => Shipment.fromJson(e)).toList()
);



