import '../bundle_meta.dart';
import '../ent/store.dart';


final storeProfile = BundleMeta(
    'Store',
    EntityMeta(
        "ProductStore",
        [
          FieldMeta("productStoreId", "id"),
          FieldMeta("primaryStoreGroupId", "id"),
          FieldMeta("storeName", "name"),
          FieldMeta("companyName", "name"),
          FieldMeta("title", "name"),
          FieldMeta("subtitle", "description"),
          FieldMeta("payToPartyId", "id"),
          FieldMeta("daysToCancelNonPay", "numeric"),
          FieldMeta("manualAuthIsCapture", "indicator"),
          FieldMeta("prorateShipping", "indicator"),
          FieldMeta("prorateTaxes", "indicator"),
          FieldMeta("viewCartOnAdd", "indicator"),
          FieldMeta("autoSaveCart", "indicator"),
          FieldMeta("autoApproveReviews", "indicator"),
          FieldMeta("isDemoStore", "indicator"),
          FieldMeta("isImmediatelyFulfilled", "indicator"),
          FieldMeta("inventoryFacilityId", "id"),
          FieldMeta("oneInventoryFacility", "indicator"),
          FieldMeta("checkInventory", "indicator"),
          FieldMeta("reserveInventory", "indicator"),
          FieldMeta("reserveOrderEnumId", "id"),
          FieldMeta("requireInventory", "indicator"),
          FieldMeta("balanceResOnOrderCreation", "indicator"),
          FieldMeta("requirementMethodEnumId", "id"),
          FieldMeta("orderNumberPrefix", "id-long"),
          FieldMeta("defaultLocaleString", "very-short"),
          FieldMeta("defaultCurrencyUomId", "id"),
          FieldMeta("defaultTimeZoneString", "id-long"),
          FieldMeta("defaultSalesChannelEnumId", "id"),
          FieldMeta("allowPassword", "indicator"),
          FieldMeta("defaultPassword", "long-varchar"),
          FieldMeta("explodeOrderItems", "indicator"),
          FieldMeta("checkGcBalance", "indicator"),
          FieldMeta("retryFailedAuths", "indicator"),
          FieldMeta("headerApprovedStatus", "id"),
          FieldMeta("itemApprovedStatus", "id"),
          FieldMeta("digitalItemApprovedStatus", "id"),
          FieldMeta("headerDeclinedStatus", "id"),
          FieldMeta("itemDeclinedStatus", "id"),
          FieldMeta("headerCancelStatus", "id"),
          FieldMeta("itemCancelStatus", "id"),
          FieldMeta("authDeclinedMessage", "long-varchar"),
          FieldMeta("authFraudMessage", "long-varchar"),
          FieldMeta("authErrorMessage", "long-varchar"),
          FieldMeta("visualThemeId", "id"),
          FieldMeta("storeCreditAccountEnumId", "id"),
          FieldMeta("usePrimaryEmailUsername", "indicator"),
          FieldMeta("requireCustomerRole", "indicator"),
          FieldMeta("autoInvoiceDigitalItems", "indicator"),
          FieldMeta("reqShipAddrForDigItems", "indicator"),
          FieldMeta("showCheckoutGiftOptions", "indicator"),
          FieldMeta("selectPaymentTypePerItem", "indicator"),
          FieldMeta("showPricesWithVatTax", "indicator"),
          FieldMeta("showTaxIsExempt", "indicator"),
          FieldMeta("vatTaxAuthGeoId", "id"),
          FieldMeta("vatTaxAuthPartyId", "id"),
          FieldMeta("enableAutoSuggestionList", "indicator"),
          FieldMeta("enableDigProdUpload", "indicator"),
          FieldMeta("prodSearchExcludeVariants", "indicator"),
          FieldMeta("digProdUploadCategoryId", "id"),
          FieldMeta("autoOrderCcTryExp", "indicator"),
          FieldMeta("autoOrderCcTryOtherCards", "indicator"),
          FieldMeta("autoOrderCcTryLaterNsf", "indicator"),
          FieldMeta("autoOrderCcTryLaterMax", "numeric"),
          FieldMeta("storeCreditValidDays", "numeric"),
          FieldMeta("autoApproveInvoice", "indicator"),
          FieldMeta("autoApproveOrder", "indicator"),
          FieldMeta("shipIfCaptureFails", "indicator"),
          FieldMeta("setOwnerUponIssuance", "indicator"),
          FieldMeta("reqReturnInventoryReceive", "indicator"),
          FieldMeta("addToCartRemoveIncompat", "indicator"),
          FieldMeta("addToCartReplaceUpsell", "indicator"),
          FieldMeta("splitPayPrefPerShpGrp", "indicator"),
          FieldMeta("managedByLot", "indicator"),
          FieldMeta("showOutOfStockProducts", "indicator"),
          FieldMeta("orderDecimalQuantity", "indicator"),
          FieldMeta("allowComment", "indicator"),
          FieldMeta("allocateInventory", "indicator"),
          FieldMeta("lastUpdatedTxStamp", "date-time"),
          FieldMeta("createdTxStamp", "date-time"),
          FieldMeta("tenantId", "id"),
          FieldMeta("evict", "boolean"),
          FieldMeta("tag1", "name"),
          FieldMeta("tag2", "name"),
          FieldMeta("tag3", "name"),
          FieldMeta("moreTags", "strings"),
          FieldMeta("jointers", "string-map"),
          FieldMeta("multiJointers", "string-multimap"),
          FieldMeta("acl", "string-multimap"),
          FieldMeta("telephone", "tel-number"),
          FieldMeta("email", "email"),
          FieldMeta("placeId", "id"),
          FieldMeta("xcPrimaryStoreGroupId", "xid"),
          FieldMeta("xcInventoryFacilityId", "xid"),
          FieldMeta("xcPayToPartyId", "xid"),
          FieldMeta("xcPlaceId", "xid"),
        ],
        'productStoreId',
    ),
    {},    
    cast: (json) => Store.fromJson(json),
    list: (List rs) => rs.map((e) => Store.fromJson(e)).toList()
);



