name: annotations
description: Annotations for generators.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
  test: any

