name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path:
  build:
  source_gen:
  glob:
  sqlite3:
  tuple:
  annotations:
    path: ../annotations/

dev_dependencies:
  build_test:
  build_runner:
  test: any
