name: cells
description: Cells library
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  crypto: ^3.0.0
  dio: ^5.1.2
  equatable: ^2.0.5
  recase: ^4.0.0
  slugid: ^1.1.0
  intl: ^0.19.0
  validators: ^3.0.0
  power_extensions: ^0.2.2
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.0.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  clock: any
  copy_with_extension: ^4.0.3
  xcsproto:
    path: ../xcsproto
  xcsapi:
    path: ../xcsapi

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  pedantic: ^1.10.0
  json_serializable: ^6.3.0
  build_runner: ^2.1.8
  freezed: ^2.1.0+1
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
