targets:
  $default:
    builders:
#      generators|generators:
#        enabled: true

      generators|sql_builder:
        enabled: true
        generate_for:
          include:
            - lib/models/**.dart

      # The end-user of a builder which applies "source_gen|combining_builder"
      # may configure the builder to ignore specific lints for their project
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - lint_a
            - lint_b