import 'package:xcsmachine/util.dart';

final reclets = [configuratorAndDetailForm, signupForm, palletEntryForm, skuInfoForm, configuratorForm, protoEntForm, noteContentForm, metaEntryForm, shelfForm, configItemForm, userInfoForm, configOptForm, testRecForm, spuInfoForm, helloPojoForm, commodityForm, fullIdForm, userObjForm]; 

final rectiles = [noteContentTile, userObjTile];

/// map of <FormMeta>
final recletsMap= reclets.map((el)=>MapEntry(el['formName'] as String, el)).toMap();
/// map of <TileMeta>
final rectilesMap= rectiles.map((el)=>MapEntry(el['tileName'] as String, el)).toMap();


final configuratorAndDetailForm = {
  "formKey" : "ConfiguratorAndDetail",
  "formName" : "ConfiguratorAndDetail",
  "alias" : "configuratorAndDetail",
  "caption" : "Configurator And Detail",
  "locale" : "zh",
  "keyFld" : "key",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "configurator" : {
      "fldName" : "configurator",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Configurator",
      "hint" : "Configurator",
      "defaultValue" : null,
      "morph" : "Configurator",
      "dartType" : "Configurator",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "variants" : {
      "fldName" : "variants",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Variants",
      "hint" : "Variants",
      "defaultValue" : "<bi:Product>[]",
      "morph" : "bi:Product",
      "dartType" : "List<bi:Product>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "feats" : {
      "fldName" : "feats",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Feats",
      "hint" : "Feats",
      "defaultValue" : "<bi:ProductFeature>[]",
      "morph" : "bi:ProductFeature",
      "dartType" : "List<bi:ProductFeature>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "key" : {
      "fldName" : "key",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Key",
      "hint" : "Key",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final signupForm = {
  "formKey" : "Signup",
  "formName" : "Signup",
  "alias" : "signup",
  "caption" : "Signup",
  "locale" : "zh",
  "keyFld" : "fullName",
  "labelSubmit" : "注册",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "password" : {
      "fldName" : "password",
      "fldType" : "password",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "密码",
      "hint" : "密码",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "acceptTerms" : {
      "fldName" : "acceptTerms",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "我已经阅读且接受该服务协议.",
      "hint" : "我已经阅读且接受该服务协议.",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fullName" : {
      "fldName" : "fullName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Full Name",
      "hint" : "Full Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "confirmPassword" : {
      "fldName" : "confirmPassword",
      "fldType" : "password",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Confirm Password",
      "hint" : "Confirm Password",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "email" : {
      "fldName" : "email",
      "fldType" : "email",
      "fldTpl" : "emailProp",
      "domainType" : "stringField",
      "caption" : "电子邮件",
      "hint" : "电子邮件",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final palletEntryForm = {
  "formKey" : "PalletEntry",
  "formName" : "PalletEntry",
  "alias" : "palletEntry",
  "caption" : "Pallet Entry",
  "locale" : "zh",
  "keyFld" : "palletName",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "syncName" : {
      "fldName" : "syncName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Sync Name",
      "hint" : "Sync Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "palletVar" : {
      "fldName" : "palletVar",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Pallet Var",
      "hint" : "Pallet Var",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "bundleName" : {
      "fldName" : "bundleName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Bundle Name",
      "hint" : "Bundle Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "flatMessageType" : {
      "fldName" : "flatMessageType",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Flat Message Type",
      "hint" : "Flat Message Type",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "palletSymbol" : {
      "fldName" : "palletSymbol",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Pallet Symbol",
      "hint" : "Pallet Symbol",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "mainEnt" : {
      "fldName" : "mainEnt",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Main Ent",
      "hint" : "Main Ent",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "palletName" : {
      "fldName" : "palletName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Pallet Name",
      "hint" : "Pallet Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "totalActions" : {
      "fldName" : "totalActions",
      "fldType" : "integer",
      "fldTpl" : "propWithSpec",
      "domainType" : "floatField",
      "caption" : "Total Actions",
      "hint" : "Total Actions",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Integer",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fullSyncName" : {
      "fldName" : "fullSyncName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Full Sync Name",
      "hint" : "Full Sync Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "palletFullName" : {
      "fldName" : "palletFullName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Pallet Full Name",
      "hint" : "Pallet Full Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "callType" : {
      "fldName" : "callType",
      "fldType" : "tag",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "Call Type",
      "hint" : "Call Type",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : "CallType",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fullFlatMessageType" : {
      "fldName" : "fullFlatMessageType",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Full Flat Message Type",
      "hint" : "Full Flat Message Type",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final skuInfoForm = {
  "formKey" : "SkuInfo",
  "formName" : "SkuInfo",
  "alias" : "skuInfo",
  "caption" : "Sku Info",
  "locale" : "zh",
  "keyFld" : "id",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "skuName" : {
      "fldName" : "skuName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Sku Name",
      "hint" : "Sku Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "serialVersionUID" : {
      "fldName" : "serialVersionUID",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Serial Version UID",
      "hint" : "Serial Version UID",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "tmId" : {
      "fldName" : "tmId",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Tm Id",
      "hint" : "Tm Id",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "createTime" : {
      "fldName" : "createTime",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "Create Time",
      "hint" : "Create Time",
      "defaultValue" : null,
      "morph" : "LocalDateTime",
      "dartType" : "LocalDateTime",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "price" : {
      "fldName" : "price",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Price",
      "hint" : "Price",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "category3Id" : {
      "fldName" : "category3Id",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Category3 Id",
      "hint" : "Category3 Id",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "weight" : {
      "fldName" : "weight",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Weight",
      "hint" : "Weight",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "skuDefaultImg" : {
      "fldName" : "skuDefaultImg",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Sku Default Img",
      "hint" : "Sku Default Img",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "spuId" : {
      "fldName" : "spuId",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Spu Id",
      "hint" : "Spu Id",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "skuDesc" : {
      "fldName" : "skuDesc",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Sku Desc",
      "hint" : "Sku Desc",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "id" : {
      "fldName" : "id",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Id",
      "hint" : "Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final configuratorForm = {
  "formKey" : "Configurator",
  "formName" : "Configurator",
  "alias" : "configurator",
  "caption" : "Configurator",
  "locale" : "zh",
  "keyFld" : "productId",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "configs" : {
      "fldName" : "configs",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Configs",
      "hint" : "Configs",
      "defaultValue" : "<ConfigItem>[]",
      "morph" : "ConfigItem",
      "dartType" : "List<ConfigItem>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "productId" : {
      "fldName" : "productId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Product Id",
      "hint" : "Product Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final protoEntForm = {
  "formKey" : "ProtoEnt",
  "formName" : "ProtoEnt",
  "alias" : "protoEnt",
  "caption" : "Proto Ent",
  "locale" : "zh",
  "keyFld" : "key",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "entType" : {
      "fldName" : "entType",
      "fldType" : "tag",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "Ent Type",
      "hint" : "Ent Type",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : "EntityEnum",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "data" : {
      "fldName" : "data",
      "fldType" : "byte-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "bytesField",
      "caption" : "Data",
      "hint" : "Data",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "Uint8List",
      "javaType" : "byte[]",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "regionId" : {
      "fldName" : "regionId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Region Id",
      "hint" : "Region Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "lastTs" : {
      "fldName" : "lastTs",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Last Ts",
      "hint" : "Last Ts",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "key" : {
      "fldName" : "key",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Key",
      "hint" : "Key",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final noteContentForm = {
  "formKey" : "NoteContent",
  "formName" : "NoteContent",
  "alias" : "noteContent",
  "caption" : "便笺内容",
  "locale" : "zh",
  "keyFld" : "key",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "title" : {
      "fldName" : "title",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "标题",
      "hint" : "标题",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "body" : {
      "fldName" : "body",
      "fldType" : "value",
      "fldTpl" : "commentProp",
      "domainType" : "stringField",
      "caption" : "内容",
      "hint" : "内容",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "key" : {
      "fldName" : "key",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Key",
      "hint" : "Key",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final metaEntryForm = {
  "formKey" : "MetaEntry",
  "formName" : "MetaEntry",
  "alias" : "metaEntry",
  "caption" : "Meta Entry",
  "locale" : "zh",
  "keyFld" : "entityName",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "syncName" : {
      "fldName" : "syncName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Sync Name",
      "hint" : "Sync Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "plugName" : {
      "fldName" : "plugName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Plug Name",
      "hint" : "Plug Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "entityName" : {
      "fldName" : "entityName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Entity Name",
      "hint" : "Entity Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "flatMessageType" : {
      "fldName" : "flatMessageType",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Flat Message Type",
      "hint" : "Flat Message Type",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "bundleName" : {
      "fldName" : "bundleName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Bundle Name",
      "hint" : "Bundle Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "syncNs" : {
      "fldName" : "syncNs",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Sync Ns",
      "hint" : "Sync Ns",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "packageName" : {
      "fldName" : "packageName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Package Name",
      "hint" : "Package Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fields" : {
      "fldName" : "fields",
      "fldType" : "strings",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringsField",
      "caption" : "Fields",
      "hint" : "Fields",
      "defaultValue" : "<String>[]",
      "morph" : "",
      "dartType" : "List<String?>",
      "javaType" : "com.bluecc.hubs.stub.Strings",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fullSyncName" : {
      "fldName" : "fullSyncName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Full Sync Name",
      "hint" : "Full Sync Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "fullFlatMessageType" : {
      "fldName" : "fullFlatMessageType",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Full Flat Message Type",
      "hint" : "Full Flat Message Type",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final shelfForm = {
  "formKey" : "Shelf",
  "formName" : "Shelf",
  "alias" : "shelf",
  "caption" : "Shelf",
  "locale" : "zh",
  "keyFld" : "storeId",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "facilityId" : {
      "fldName" : "facilityId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Facility Id",
      "hint" : "Facility Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "goods" : {
      "fldName" : "goods",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Goods",
      "hint" : "Goods",
      "defaultValue" : "<Commodity>[]",
      "morph" : "Commodity",
      "dartType" : "List<Commodity>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "storeId" : {
      "fldName" : "storeId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Store Id",
      "hint" : "Store Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final configItemForm = {
  "formKey" : "ConfigItem",
  "formName" : "ConfigItem",
  "alias" : "configItem",
  "caption" : "Config Item",
  "locale" : "zh",
  "keyFld" : "key",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "fromDate" : {
      "fldName" : "fromDate",
      "fldType" : "date-time",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "From Date",
      "hint" : "From Date",
      "defaultValue" : "DateTime.now()",
      "morph" : "",
      "dartType" : "DateTime",
      "javaType" : "java.time.OffsetDateTime",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "defaultConfigOptionId" : {
      "fldName" : "defaultConfigOptionId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Default Config Option Id",
      "hint" : "Default Config Option Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "seqNum" : {
      "fldName" : "seqNum",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Seq Num",
      "hint" : "Seq Num",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "configTypeId" : {
      "fldName" : "configTypeId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Config Type Id",
      "hint" : "Config Type Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "configItemName" : {
      "fldName" : "configItemName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Config Item Name",
      "hint" : "Config Item Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "description" : {
      "fldName" : "description",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "描述",
      "hint" : "描述",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "itemDesc" : {
      "fldName" : "itemDesc",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Item Desc",
      "hint" : "Item Desc",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "mandatory" : {
      "fldName" : "mandatory",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "Mandatory",
      "hint" : "Mandatory",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "items" : {
      "fldName" : "items",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Items",
      "hint" : "Items",
      "defaultValue" : "<ConfigOpt>[]",
      "morph" : "ConfigOpt",
      "dartType" : "List<ConfigOpt>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "key" : {
      "fldName" : "key",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Key",
      "hint" : "Key",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final userInfoForm = {
  "formKey" : "UserInfo",
  "formName" : "UserInfo",
  "alias" : "userInfo",
  "caption" : "User Info",
  "locale" : "zh",
  "keyFld" : "id",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "birthday" : {
      "fldName" : "birthday",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "出生日期",
      "hint" : "出生日期",
      "defaultValue" : null,
      "morph" : "LocalDateTime",
      "dartType" : "LocalDateTime",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "headImg" : {
      "fldName" : "headImg",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Head Img",
      "hint" : "Head Img",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "gender" : {
      "fldName" : "gender",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "性别",
      "hint" : "性别",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "nickName" : {
      "fldName" : "nickName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Nick Name",
      "hint" : "Nick Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "operateTime" : {
      "fldName" : "operateTime",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "Operate Time",
      "hint" : "Operate Time",
      "defaultValue" : null,
      "morph" : "LocalDateTime",
      "dartType" : "LocalDateTime",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "phoneNum" : {
      "fldName" : "phoneNum",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Phone Num",
      "hint" : "Phone Num",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "serialVersionUID" : {
      "fldName" : "serialVersionUID",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Serial Version UID",
      "hint" : "Serial Version UID",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "userLevel" : {
      "fldName" : "userLevel",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "User Level",
      "hint" : "User Level",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "passwd" : {
      "fldName" : "passwd",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Passwd",
      "hint" : "Passwd",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "createTime" : {
      "fldName" : "createTime",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "Create Time",
      "hint" : "Create Time",
      "defaultValue" : null,
      "morph" : "LocalDateTime",
      "dartType" : "LocalDateTime",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "loginName" : {
      "fldName" : "loginName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Login Name",
      "hint" : "Login Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "name" : {
      "fldName" : "name",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "名称",
      "hint" : "名称",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "id" : {
      "fldName" : "id",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Id",
      "hint" : "Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "email" : {
      "fldName" : "email",
      "fldType" : "email",
      "fldTpl" : "emailProp",
      "domainType" : "stringField",
      "caption" : "电子邮件",
      "hint" : "电子邮件",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final configOptForm = {
  "formKey" : "ConfigOpt",
  "formName" : "ConfigOpt",
  "alias" : "configOpt",
  "caption" : "Config Opt",
  "locale" : "zh",
  "keyFld" : "configOptionId",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "quantity" : {
      "fldName" : "quantity",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Quantity",
      "hint" : "Quantity",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "productId" : {
      "fldName" : "productId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Product Id",
      "hint" : "Product Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "configOptionId" : {
      "fldName" : "configOptionId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Config Option Id",
      "hint" : "Config Option Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "selectableFeats" : {
      "fldName" : "selectableFeats",
      "fldType" : "strings",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringsField",
      "caption" : "Selectable Feats",
      "hint" : "Selectable Feats",
      "defaultValue" : "<String>[]",
      "morph" : "",
      "dartType" : "List<String?>",
      "javaType" : "com.bluecc.hubs.stub.Strings",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "description" : {
      "fldName" : "description",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "描述",
      "hint" : "描述",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "variants" : {
      "fldName" : "variants",
      "fldType" : "strings",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringsField",
      "caption" : "Variants",
      "hint" : "Variants",
      "defaultValue" : "<String>[]",
      "morph" : "",
      "dartType" : "List<String?>",
      "javaType" : "com.bluecc.hubs.stub.Strings",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final testRecForm = {
  "formKey" : "TestRec",
  "formName" : "TestRec",
  "alias" : "testRec",
  "caption" : "Test Rec",
  "locale" : "zh",
  "keyFld" : "stringFld",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "numFld" : {
      "fldName" : "numFld",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Num Fld",
      "hint" : "Num Fld",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "stringFld" : {
      "fldName" : "stringFld",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "String Fld",
      "hint" : "String Fld",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "tag" : {
      "fldName" : "tag",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Tag",
      "hint" : "Tag",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "boolFld" : {
      "fldName" : "boolFld",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "Bool Fld",
      "hint" : "Bool Fld",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "numMap" : {
      "fldName" : "numMap",
      "fldType" : "decimal-map",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Num Map",
      "hint" : "Num Map",
      "defaultValue" : "{}",
      "morph" : "",
      "dartType" : "Map<String, double>",
      "javaType" : "com.bluecc.hubs.stub.DecimalMap",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "nums" : {
      "fldName" : "nums",
      "fldType" : "decimals",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Nums",
      "hint" : "Nums",
      "defaultValue" : "<double>[]",
      "morph" : "",
      "dartType" : "List<double?>",
      "javaType" : "com.bluecc.hubs.stub.Decimals",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final spuInfoForm = {
  "formKey" : "SpuInfo",
  "formName" : "SpuInfo",
  "alias" : "spuInfo",
  "caption" : "Spu Info",
  "locale" : "zh",
  "keyFld" : "id",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "serialVersionUID" : {
      "fldName" : "serialVersionUID",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Serial Version UID",
      "hint" : "Serial Version UID",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "spuName" : {
      "fldName" : "spuName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Spu Name",
      "hint" : "Spu Name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "tmId" : {
      "fldName" : "tmId",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Tm Id",
      "hint" : "Tm Id",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "category3Id" : {
      "fldName" : "category3Id",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "Category3 Id",
      "hint" : "Category3 Id",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "description" : {
      "fldName" : "description",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "描述",
      "hint" : "描述",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "id" : {
      "fldName" : "id",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Id",
      "hint" : "Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final helloPojoForm = {
  "formKey" : "HelloPojo",
  "formName" : "HelloPojo",
  "alias" : "helloPojo",
  "caption" : "你好, Pojo!",
  "locale" : "zh",
  "keyFld" : "name",
  "labelSubmit" : "好运, Pojo!",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "birthday" : {
      "fldName" : "birthday",
      "fldType" : "date-time",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateTimeField",
      "caption" : "出生日期",
      "hint" : "出生日期",
      "defaultValue" : "DateTime.now()",
      "morph" : "",
      "dartType" : "DateTime",
      "javaType" : "java.time.OffsetDateTime",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "languagesFilter" : {
      "fldName" : "languagesFilter",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Languages Filter",
      "hint" : "Languages Filter",
      "defaultValue" : "<ProgrammingLanguage>[]",
      "morph" : "ProgrammingLanguage",
      "dartType" : "List<ProgrammingLanguage>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : "ProgrammingLanguage",
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "note" : {
      "fldName" : "note",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Note",
      "hint" : "Note",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "holderName" : {
      "fldName" : "holderName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "持有人",
      "hint" : "Enter account holder name",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "gender" : {
      "fldName" : "gender",
      "fldType" : "tag",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "性别",
      "hint" : "性别",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : "Gender",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "dateRange" : {
      "fldName" : "dateRange",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Date Range",
      "hint" : "Date Range",
      "defaultValue" : null,
      "morph" : "DateTimeRange",
      "dartType" : "DateTimeRange",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "favLangs" : {
      "fldName" : "favLangs",
      "fldType" : "json-array",
      "fldTpl" : "propWithSpec",
      "domainType" : "listField",
      "caption" : "Fav Langs",
      "hint" : "Fav Langs",
      "defaultValue" : "<ProgrammingLanguage>[]",
      "morph" : "ProgrammingLanguage",
      "dartType" : "List<ProgrammingLanguage>",
      "javaType" : "com.google.protobuf.ListValue",
      "enumType" : "ProgrammingLanguage",
      "collection" : true,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "acceptTerms" : {
      "fldName" : "acceptTerms",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "我已经阅读且接受该服务协议.",
      "hint" : "我已经阅读且接受该服务协议.",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "salary" : {
      "fldName" : "salary",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Salary",
      "hint" : "Salary",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "productTypeId" : {
      "fldName" : "productTypeId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "产品类型ID",
      "hint" : "产品类型ID",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : {
        "name" : "typeListControl",
        "mandatory" : false,
        "sels" : "productTypes"
      },
      "binders" : null,
      "slider" : null
    },
    "numberOfThings" : {
      "fldName" : "numberOfThings",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Number Of Things",
      "hint" : "Number Of Things",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : {
        "min" : 0.0,
        "max" : 10.0,
        "divisions" : 20
      }
    },
    "employed" : {
      "fldName" : "employed",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "是否在职?",
      "hint" : "是否在职?",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "password" : {
      "fldName" : "password",
      "fldType" : "password",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "密码",
      "hint" : "密码",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "bestLanguage" : {
      "fldName" : "bestLanguage",
      "fldType" : "tag",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "Best Language",
      "hint" : "Best Language",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : "ProgrammingLanguage",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "rate" : {
      "fldName" : "rate",
      "fldType" : "floating-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "floatField",
      "caption" : "Rate",
      "hint" : "Rate",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "double",
      "javaType" : "Double",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "name" : {
      "fldName" : "name",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "名称",
      "hint" : "名称",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "weightUomId" : {
      "fldName" : "weightUomId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Weight Uom Id",
      "hint" : "Weight Uom Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : {
        "name" : "typeListControl",
        "mandatory" : false,
        "sels" : "weightTypes"
      },
      "binders" : null,
      "slider" : null
    },
    "confirmPassword" : {
      "fldName" : "confirmPassword",
      "fldType" : "password",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Confirm Password",
      "hint" : "Confirm Password",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : [ {
        "kind" : "required",
        "role" : "default",
        "target" : "password"
      } ],
      "slider" : null
    },
    "targetUser" : {
      "fldName" : "targetUser",
      "fldType" : "strings",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringsField",
      "caption" : "目标用户",
      "hint" : "目标用户",
      "defaultValue" : "<String>[]",
      "morph" : "",
      "dartType" : "List<String?>",
      "javaType" : "com.bluecc.hubs.stub.Strings",
      "enumType" : null,
      "collection" : true,
      "fldSpec" : {
        "name" : "typeListControl",
        "mandatory" : false,
        "sels" : "partyTypes"
      },
      "binders" : null,
      "slider" : null
    },
    "priceRange" : {
      "fldName" : "priceRange",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Price Range",
      "hint" : "Price Range",
      "defaultValue" : null,
      "morph" : "NumberRange",
      "dartType" : "NumberRange",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : {
        "min" : 0.0,
        "max" : 100.0,
        "divisions" : 20
      }
    },
    "age" : {
      "fldName" : "age",
      "fldType" : "integer",
      "fldTpl" : "propWithSpec",
      "domainType" : "floatField",
      "caption" : "年龄",
      "hint" : "年龄",
      "defaultValue" : "0",
      "morph" : "",
      "dartType" : "int",
      "javaType" : "Integer",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "email" : {
      "fldName" : "email",
      "fldType" : "email",
      "fldTpl" : "emailProp",
      "domainType" : "stringField",
      "caption" : "电子邮件",
      "hint" : "电子邮件",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "myChosenLanguage" : {
      "fldName" : "myChosenLanguage",
      "fldType" : "tag",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "My Chosen Language",
      "hint" : "My Chosen Language",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : "ProgrammingLanguage",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "widthUomId" : {
      "fldName" : "widthUomId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Width Uom Id",
      "hint" : "Width Uom Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : {
        "name" : "typeListControl",
        "mandatory" : false,
        "sels" : "widthTypes"
      },
      "binders" : null,
      "slider" : null
    }
  }
};

final commodityForm = {
  "formKey" : "Commodity",
  "formName" : "Commodity",
  "alias" : "commodity",
  "caption" : "Commodity",
  "locale" : "zh",
  "keyFld" : "id",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "unitPrice" : {
      "fldName" : "unitPrice",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Unit Price",
      "hint" : "Unit Price",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "image" : {
      "fldName" : "image",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Image",
      "hint" : "Image",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "featured" : {
      "fldName" : "featured",
      "fldType" : "boolean",
      "fldTpl" : "propWithSpec",
      "domainType" : "boolField",
      "caption" : "Featured",
      "hint" : "Featured",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "bool",
      "javaType" : "Boolean",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "product" : {
      "fldName" : "product",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Product",
      "hint" : "Product",
      "defaultValue" : null,
      "morph" : "bi:Product",
      "dartType" : "bi:Product",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "configurator" : {
      "fldName" : "configurator",
      "fldType" : "json-object",
      "fldTpl" : "propWithSpec",
      "domainType" : "structField",
      "caption" : "Configurator",
      "hint" : "Configurator",
      "defaultValue" : null,
      "morph" : "ConfiguratorAndDetail",
      "dartType" : "ConfiguratorAndDetail",
      "javaType" : "com.google.protobuf.Struct",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "quantity" : {
      "fldName" : "quantity",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Quantity",
      "hint" : "Quantity",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "facilityId" : {
      "fldName" : "facilityId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Facility Id",
      "hint" : "Facility Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "productId" : {
      "fldName" : "productId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Product Id",
      "hint" : "Product Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "name" : {
      "fldName" : "name",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "名称",
      "hint" : "名称",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "description" : {
      "fldName" : "description",
      "fldType" : "description",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "描述",
      "hint" : "描述",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "id" : {
      "fldName" : "id",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Id",
      "hint" : "Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final fullIdForm = {
  "formKey" : "FullId",
  "formName" : "FullId",
  "alias" : "fullId",
  "caption" : "Full Id",
  "locale" : "zh",
  "keyFld" : "id",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "regionId" : {
      "fldName" : "regionId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Region Id",
      "hint" : "Region Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "id" : {
      "fldName" : "id",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Id",
      "hint" : "Id",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final userObjForm = {
  "formKey" : "UserObj",
  "formName" : "UserObj",
  "alias" : "userObj",
  "caption" : "User Obj",
  "locale" : "zh",
  "keyFld" : "partyId",
  "labelSubmit" : "Submit",
  "labelReset" : "Reset",
  "profile" : null,
  "flds" : {
    "lastName" : {
      "fldName" : "lastName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "姓",
      "hint" : "姓",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "gender" : {
      "fldName" : "gender",
      "fldType" : "indicator",
      "fldTpl" : "propWithSpec",
      "domainType" : "idenField",
      "caption" : "性别",
      "hint" : "性别",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "String",
      "javaType" : "Character",
      "enumType" : "Indicator",
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "color" : {
      "fldName" : "color",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "颜色",
      "hint" : "颜色",
      "defaultValue" : "Colors.grey",
      "morph" : "",
      "dartType" : "Color",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "icon" : {
      "fldName" : "icon",
      "fldType" : "numeric",
      "fldTpl" : "propWithSpec",
      "domainType" : "integerField",
      "caption" : "图标",
      "hint" : "图标",
      "defaultValue" : "Icons.account_circle",
      "morph" : "",
      "dartType" : "IconData",
      "javaType" : "Long",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "birthDate" : {
      "fldName" : "birthDate",
      "fldType" : "date",
      "fldTpl" : "propWithSpec",
      "domainType" : "dateField",
      "caption" : "出生日期",
      "hint" : "出生日期",
      "defaultValue" : "DateTime.now()",
      "morph" : "",
      "dartType" : "DateTime",
      "javaType" : "java.time.LocalDate",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "labels" : {
      "fldName" : "labels",
      "fldType" : "string-multimap",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringMultimapField",
      "caption" : "Labels",
      "hint" : "Labels",
      "defaultValue" : null,
      "morph" : "",
      "dartType" : "Multimap<String, String>",
      "javaType" : "com.bluecc.hubs.stub.StringMultimap",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "firstName" : {
      "fldName" : "firstName",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "名",
      "hint" : "名",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "balance" : {
      "fldName" : "balance",
      "fldType" : "fixed-point",
      "fldTpl" : "propWithSpec",
      "domainType" : "decimalField",
      "caption" : "Balance",
      "hint" : "Balance",
      "defaultValue" : "0.0",
      "morph" : "",
      "dartType" : "double",
      "javaType" : "java.math.BigDecimal",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "name" : {
      "fldName" : "name",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "名称",
      "hint" : "名称",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "nickname" : {
      "fldName" : "nickname",
      "fldType" : "name",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "呢称",
      "hint" : "呢称",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "partyId" : {
      "fldName" : "partyId",
      "fldType" : "id",
      "fldTpl" : "propWithSpec",
      "domainType" : "stringField",
      "caption" : "Party ID",
      "hint" : "Party ID",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "createdByUserLogin" : {
      "fldName" : "createdByUserLogin",
      "fldType" : "value",
      "fldTpl" : "valueProp",
      "domainType" : "stringField",
      "caption" : "Created By User Login",
      "hint" : "Created By User Login",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    },
    "email" : {
      "fldName" : "email",
      "fldType" : "email",
      "fldTpl" : "emailProp",
      "domainType" : "stringField",
      "caption" : "电子邮件",
      "hint" : "电子邮件",
      "defaultValue" : "''",
      "morph" : "",
      "dartType" : "String",
      "javaType" : "String",
      "enumType" : null,
      "collection" : false,
      "fldSpec" : null,
      "binders" : null,
      "slider" : null
    }
  }
};

final noteContentTile = {
  "tileName" : "NoteContent",
  "alias" : "noteContent",
  "available" : true,
  "flds" : {
    "subtitle" : {
      "loc" : "subtitle",
      "fld" : {
        "fldName" : "body",
        "fldType" : "value",
        "fldTpl" : "commentProp",
        "domainType" : "stringField",
        "caption" : "内容",
        "hint" : "内容",
        "defaultValue" : "''",
        "morph" : "",
        "dartType" : "String",
        "javaType" : "String",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "title" : {
      "loc" : "title",
      "fld" : {
        "fldName" : "title",
        "fldType" : "value",
        "fldTpl" : "valueProp",
        "domainType" : "stringField",
        "caption" : "标题",
        "hint" : "标题",
        "defaultValue" : "''",
        "morph" : "",
        "dartType" : "String",
        "javaType" : "String",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    }
  },
  "locs" : {
    "subtitle" : "body",
    "title" : "title"
  }
};

final userObjTile = {
  "tileName" : "UserObj",
  "alias" : "userObj",
  "available" : true,
  "flds" : {
    "date" : {
      "loc" : "date",
      "fld" : {
        "fldName" : "birthDate",
        "fldType" : "date",
        "fldTpl" : "propWithSpec",
        "domainType" : "dateField",
        "caption" : "出生日期",
        "hint" : "出生日期",
        "defaultValue" : "DateTime.now()",
        "morph" : "",
        "dartType" : "DateTime",
        "javaType" : "java.time.LocalDate",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "color" : {
      "loc" : "color",
      "fld" : {
        "fldName" : "color",
        "fldType" : "numeric",
        "fldTpl" : "propWithSpec",
        "domainType" : "integerField",
        "caption" : "颜色",
        "hint" : "颜色",
        "defaultValue" : "Colors.grey",
        "morph" : "",
        "dartType" : "Color",
        "javaType" : "Long",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "subtitle" : {
      "loc" : "subtitle",
      "fld" : {
        "fldName" : "nickname",
        "fldType" : "name",
        "fldTpl" : "propWithSpec",
        "domainType" : "stringField",
        "caption" : "呢称",
        "hint" : "呢称",
        "defaultValue" : "''",
        "morph" : "",
        "dartType" : "String",
        "javaType" : "String",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "icon" : {
      "loc" : "icon",
      "fld" : {
        "fldName" : "icon",
        "fldType" : "numeric",
        "fldTpl" : "propWithSpec",
        "domainType" : "integerField",
        "caption" : "图标",
        "hint" : "图标",
        "defaultValue" : "Icons.account_circle",
        "morph" : "",
        "dartType" : "IconData",
        "javaType" : "Long",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "title" : {
      "loc" : "title",
      "fld" : {
        "fldName" : "name",
        "fldType" : "name",
        "fldTpl" : "propWithSpec",
        "domainType" : "stringField",
        "caption" : "名称",
        "hint" : "名称",
        "defaultValue" : "''",
        "morph" : "",
        "dartType" : "String",
        "javaType" : "String",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    },
    "user" : {
      "loc" : "user",
      "fld" : {
        "fldName" : "createdByUserLogin",
        "fldType" : "value",
        "fldTpl" : "valueProp",
        "domainType" : "stringField",
        "caption" : "Created By User Login",
        "hint" : "Created By User Login",
        "defaultValue" : "''",
        "morph" : "",
        "dartType" : "String",
        "javaType" : "String",
        "enumType" : null,
        "collection" : false,
        "fldSpec" : null,
        "binders" : null,
        "slider" : null
      }
    }
  },
  "locs" : {
    "date" : "birthDate",
    "color" : "color",
    "subtitle" : "nickname",
    "icon" : "icon",
    "title" : "name",
    "user" : "createdByUserLogin"
  }
};