name: xcsdrift
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  drift: ^2.21.0
  # it is important that drift_dev is a regular dependency here.
  drift_dev: ^2.21.0
  quiver: ^3.2.2
  xcsmachine:
    path: ../xcsmachine
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  recase: ^4.1.0
  jiffy: ^6.3.1
  faker: ^2.2.0
  pinyin: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  json_serializable: ^6.3.0
  # for riverpod
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
